************************************************************************************************
** Procedure 3 IDENTIFY CORPORATES
**
** This section attempts to identify corporates by looking for words such as "INC".
** A flag is set if such words are found. 
** Recode of non-corporates by BHH to use KUL list of company terms.
* jb 1/15/08 index=>strpos
************************************************************************************************

replace asstype = "firm" if strpos(standard_name," & BRO ")>0
replace asstype = "firm" if strpos(standard_name," & BROTHER ")>0
replace asstype = "firm" if strpos(standard_name," & C ")>0
replace asstype = "firm" if strpos(standard_name," & CIE ")>0
replace asstype = "firm" if strpos(standard_name," & CO ")>0
replace asstype = "firm" if strpos(standard_name," & FILS ")>0
replace asstype = "firm" if strpos(standard_name," & PARTNER ")>0
replace asstype = "firm" if strpos(standard_name," & SOEHNE ")>0
replace asstype = "firm" if strpos(standard_name," & SOHN ")>0
replace asstype = "firm" if strpos(standard_name," & SON ")>0
replace asstype = "firm" if strpos(standard_name," & SONS ")>0
replace asstype = "firm" if strpos(standard_name," & ZN ")>0
replace asstype = "firm" if strpos(standard_name," & ZONEN ")>0
replace asstype = "firm" if strpos(standard_name," A ")>0
replace asstype = "firm" if strpos(standard_name," A G ")>0
replace asstype = "firm" if strpos(standard_name," A RL ")>0
replace asstype = "firm" if strpos(standard_name," A S ")>0
replace asstype = "firm" if strpos(standard_name," AANSPRAKELIJKHEID ")>0
replace asstype = "firm" if strpos(standard_name," AB ")>0
replace asstype = "firm" if strpos(standard_name," ACTIEN GESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," ACTIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AD ")>0
replace asstype = "firm" if strpos(standard_name," ADVIESBUREAU ")>0
replace asstype = "firm" if strpos(standard_name," AE ")>0
replace asstype = "firm" if strpos(standard_name," AG ")>0
replace asstype = "firm" if strpos(standard_name," AG & CO ")>0
replace asstype = "firm" if strpos(standard_name," AGG ")>0
replace asstype = "firm" if strpos(standard_name," AGSA ")>0
replace asstype = "firm" if strpos(standard_name," AK TIEBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKIEBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKIEBOLG ")>0
replace asstype = "firm" if strpos(standard_name," AKIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKITENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKITIEBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKLIENGISELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKSJESELSKAP ")>0
replace asstype = "firm" if strpos(standard_name," AKSJESELSKAPET ")>0
replace asstype = "firm" if strpos(standard_name," AKSTIEBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTAINGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTEIBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTEINGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIE BOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBDAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBLOAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOALG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOALGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOCAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLAC ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLAF ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLAQ ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEBOLOG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEGBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEGOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTIELBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEN ")>0
replace asstype = "firm" if strpos(standard_name," AKTIEN GESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENEGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENEGSELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGEGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESCELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELL SCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLESCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLESHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLS ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCGAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCHART ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCHATT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCHGT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSCHRAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSHAT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELLSHCAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESELSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESESCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESILLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESLLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESSELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGESSELSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGSELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENGTESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIENRESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTIESELSKAB ")>0
replace asstype = "firm" if strpos(standard_name," AKTIESELSKABET ")>0
replace asstype = "firm" if strpos(standard_name," AKTINGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNAYA KOMPANIA ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOE OBCHESTVO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOE OBSCHEDTVO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOE OBSCNESTVO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOE OBSHESTVO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOE OSBCHESTVO ")>0
replace asstype = "firm" if strpos(standard_name," AKTSIONERNOEOBSCHESTVO ")>0
replace asstype = "firm" if strpos(standard_name," ALTIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AMBA ")>0
replace asstype = "firm" if strpos(standard_name," AND SONS ")>0
replace asstype = "firm" if strpos(standard_name," ANDELSSELSKABET ")>0
replace asstype = "firm" if strpos(standard_name," ANLAGENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," APPARATEBAU ")>0
replace asstype = "firm" if strpos(standard_name," APPERATEBAU ")>0
replace asstype = "firm" if strpos(standard_name," ARL ")>0
replace asstype = "firm" if strpos(standard_name," AS ")>0
replace asstype = "firm" if strpos(standard_name," ASA ")>0
replace asstype = "firm" if strpos(standard_name," ASKTIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," ASOCIADOS ")>0
replace asstype = "firm" if strpos(standard_name," ASSCOIATES ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIADOS ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIATE ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIATED ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIATES ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIATI ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIATO ")>0
replace asstype = "firm" if strpos(standard_name," ASSOCIES ")>0
replace asstype = "firm" if strpos(standard_name," ASSSOCIATES ")>0
replace asstype = "firm" if strpos(standard_name," ATELIER ")>0
replace asstype = "firm" if strpos(standard_name," ATELIERS ")>0
replace asstype = "firm" if strpos(standard_name," ATIBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," ATKIEBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," ATKIENGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," AVV ")>0
replace asstype = "firm" if strpos(standard_name," B ")>0
replace asstype = "firm" if strpos(standard_name," BANK ")>0
replace asstype = "firm" if strpos(standard_name," BANQUE ")>0
replace asstype = "firm" if strpos(standard_name," BEDRIJF ")>0
replace asstype = "firm" if strpos(standard_name," BEDRIJVEN ")>0
replace asstype = "firm" if strpos(standard_name," BEPERK ")>0
replace asstype = "firm" if strpos(standard_name," BEPERKTE AANSPREEKLIJKHEID ")>0
replace asstype = "firm" if strpos(standard_name," BESCHRAENKTER HAFTUNG ")>0
replace asstype = "firm" if strpos(standard_name," BESCHRANKTER ")>0
replace asstype = "firm" if strpos(standard_name," BESCHRANKTER HAFTUNG ")>0
replace asstype = "firm" if strpos(standard_name," BESLOTENGENOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," BESLOTENVENNOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," BETRIEBE ")>0
replace asstype = "firm" if strpos(standard_name," BMBH ")>0
replace asstype = "firm" if strpos(standard_name," BRANDS ")>0
replace asstype = "firm" if strpos(standard_name," BROS ")>0
replace asstype = "firm" if strpos(standard_name," BUSINESS ")>0
replace asstype = "firm" if strpos(standard_name," BV ")>0
replace asstype = "firm" if strpos(standard_name," BV: ")>0
replace asstype = "firm" if strpos(standard_name," BV? ")>0
replace asstype = "firm" if strpos(standard_name," BVBA ")>0
replace asstype = "firm" if strpos(standard_name," BVBASPRL ")>0
replace asstype = "firm" if strpos(standard_name," BVIO ")>0
replace asstype = "firm" if strpos(standard_name," BVSA ")>0
replace asstype = "firm" if strpos(standard_name," C{OVERSCORE O}RP ")>0
replace asstype = "firm" if strpos(standard_name," CAMPAGNIE ")>0
replace asstype = "firm" if strpos(standard_name," CAMPANY ")>0
replace asstype = "firm" if strpos(standard_name," CC ")>0
replace asstype = "firm" if strpos(standard_name," CIE ")>0
replace asstype = "firm" if strpos(standard_name," CMOPANY ")>0
replace asstype = "firm" if strpos(standard_name," CO ")>0
replace asstype = "firm" if strpos(standard_name," CO OPERATIVE ")>0
replace asstype = "firm" if strpos(standard_name," CO OPERATIVES ")>0
replace asstype = "firm" if strpos(standard_name," CO: ")>0
replace asstype = "firm" if strpos(standard_name," COFP ")>0
replace asstype = "firm" if strpos(standard_name," COIRPORATION ")>0
replace asstype = "firm" if strpos(standard_name," COMANY ")>0
replace asstype = "firm" if strpos(standard_name," COMAPANY ")>0
replace asstype = "firm" if strpos(standard_name," COMERCIAL ")>0
replace asstype = "firm" if strpos(standard_name," COMERCIO ")>0
replace asstype = "firm" if strpos(standard_name," COMMANDITE SIMPLE ")>0
replace asstype = "firm" if strpos(standard_name," COMMERCIALE ")>0
replace asstype = "firm" if strpos(standard_name," COMMERCIALISATIONS ")>0
replace asstype = "firm" if strpos(standard_name," COMNPANY ")>0
replace asstype = "firm" if strpos(standard_name," COMP ")>0
replace asstype = "firm" if strpos(standard_name," COMPAGNE ")>0
replace asstype = "firm" if strpos(standard_name," COMPAGNI ")>0
replace asstype = "firm" if strpos(standard_name," COMPAGNIE ")>0
replace asstype = "firm" if strpos(standard_name," COMPAGNIN ")>0
replace asstype = "firm" if strpos(standard_name," COMPAGNY ")>0
replace asstype = "firm" if strpos(standard_name," COMPAIGNIE ")>0
replace asstype = "firm" if strpos(standard_name," COMPAMY ")>0
replace asstype = "firm" if strpos(standard_name," COMPANAY ")>0
replace asstype = "firm" if strpos(standard_name," COMPANH ")>0
replace asstype = "firm" if strpos(standard_name," COMPANHIA ")>0
replace asstype = "firm" if strpos(standard_name," COMPANIA ")>0
replace asstype = "firm" if strpos(standard_name," COMPANIE ")>0
replace asstype = "firm" if strpos(standard_name," COMPANIES ")>0
replace asstype = "firm" if strpos(standard_name," COMPANY ")>0
replace asstype = "firm" if strpos(standard_name," COMPAY ")>0
replace asstype = "firm" if strpos(standard_name," COMPNAY ")>0
replace asstype = "firm" if strpos(standard_name," COMAPNY ")>0
replace asstype = "firm" if strpos(standard_name," COMPNY ")>0
replace asstype = "firm" if strpos(standard_name," COMPORATION ")>0
replace asstype = "firm" if strpos(standard_name," CONSORTILE PER AZIONE ")>0
replace asstype = "firm" if strpos(standard_name," CONSORZIO ")>0
replace asstype = "firm" if strpos(standard_name," CONSTRUCTIONS ")>0
replace asstype = "firm" if strpos(standard_name," CONSULTING ")>0
replace asstype = "firm" if strpos(standard_name," CONZORZIO ")>0
replace asstype = "firm" if strpos(standard_name," COOEPERATIE ")>0
replace asstype = "firm" if strpos(standard_name," COOEPERATIEVE ")>0
replace asstype = "firm" if strpos(standard_name," COOEPERATIEVE VERENIGING ")>0
replace asstype = "firm" if strpos(standard_name," COOEPERATIEVE VERKOOP ")>0
replace asstype = "firm" if strpos(standard_name," COOP ")>0
replace asstype = "firm" if strpos(standard_name," COOP A RL ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIE ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIEVE ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIEVE VENOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATION ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIVA AGICOLA ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIVA LIMITADA ")>0
replace asstype = "firm" if strpos(standard_name," COOPERATIVA PER AZIONI ")>0
replace asstype = "firm" if strpos(standard_name," COORPORATION ")>0
replace asstype = "firm" if strpos(standard_name," COPANY ")>0
replace asstype = "firm" if strpos(standard_name," COPORATION ")>0
replace asstype = "firm" if strpos(standard_name," COPR ")>0
replace asstype = "firm" if strpos(standard_name," COPRORATION ")>0
replace asstype = "firm" if strpos(standard_name," COPRPORATION ")>0
replace asstype = "firm" if strpos(standard_name," COROPORTION ")>0
replace asstype = "firm" if strpos(standard_name," COROPRATION ")>0
replace asstype = "firm" if strpos(standard_name," COROPROATION ")>0
replace asstype = "firm" if strpos(standard_name," CORORATION ")>0
replace asstype = "firm" if strpos(standard_name," CORP ")>0
replace asstype = "firm" if strpos(standard_name," CORPARATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPERATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPFORATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPN ")>0
replace asstype = "firm" if strpos(standard_name," CORPO ")>0
replace asstype = "firm" if strpos(standard_name," CORPOARTION ")>0
replace asstype = "firm" if strpos(standard_name," CORPOATAION ")>0
replace asstype = "firm" if strpos(standard_name," CORPOATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPOIRATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPOORATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPOPRATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORAATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORACION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORAION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORAITON ")>0
replace asstype = "firm" if strpos(standard_name," CORPORARION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORARTION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATAION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATE ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATED ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATI ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIN ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATINO ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATINON ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIO ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIOIN ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIOLN ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIOM ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATIOPN ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATITON ")>0
replace asstype = "firm" if strpos(standard_name," CORPORATOIN ")>0
replace asstype = "firm" if strpos(standard_name," CORPORDATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORQTION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORTAION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORTATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPORTION ")>0
replace asstype = "firm" if strpos(standard_name," CORPPORATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPRATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPROATION ")>0
replace asstype = "firm" if strpos(standard_name," CORPRORATION ")>0
replace asstype = "firm" if strpos(standard_name," CROP ")>0
replace asstype = "firm" if strpos(standard_name," CROPORATION ")>0
replace asstype = "firm" if strpos(standard_name," CRPORATION ")>0
replace asstype = "firm" if strpos(standard_name," CV ")>0
replace asstype = "firm" if strpos(standard_name," D ENTERPRISES ")>0
replace asstype = "firm" if strpos(standard_name," D ENTREPRISE ")>0
replace asstype = "firm" if strpos(standard_name," D O O ")>0
replace asstype = "firm" if strpos(standard_name," D’ENTREPRISE ")>0
replace asstype = "firm" if strpos(standard_name," DD ")>0
replace asstype = "firm" if strpos(standard_name," DEVELOP ")>0
replace asstype = "firm" if strpos(standard_name," DEVELOPPEMENT ")>0
replace asstype = "firm" if strpos(standard_name," DEVELOPPEMENTS ")>0
replace asstype = "firm" if strpos(standard_name," DOING BUSINESS ")>0
replace asstype = "firm" if strpos(standard_name," DOO ")>0
replace asstype = "firm" if strpos(standard_name," DORPORATION ")>0
replace asstype = "firm" if strpos(standard_name," EDMS ")>0
replace asstype = "firm" if strpos(standard_name," EG ")>0
replace asstype = "firm" if strpos(standard_name," ELECTRONIQUE ")>0
replace asstype = "firm" if strpos(standard_name," EN ZN ")>0
replace asstype = "firm" if strpos(standard_name," EN ZONEN ")>0
replace asstype = "firm" if strpos(standard_name," ENGINEERING ")>0
replace asstype = "firm" if strpos(standard_name," ENGINEERS ")>0
replace asstype = "firm" if strpos(standard_name," ENGINES ")>0
replace asstype = "firm" if strpos(standard_name," ENNOBLISSEMENT ")>0
replace asstype = "firm" if strpos(standard_name," ENTERPRISE ")>0
replace asstype = "firm" if strpos(standard_name," ENTRE PRISES ")>0
replace asstype = "firm" if strpos(standard_name," ENTREPOSE ")>0
replace asstype = "firm" if strpos(standard_name," ENTREPRISE ")>0
replace asstype = "firm" if strpos(standard_name," ENTREPRISES ")>0
replace asstype = "firm" if strpos(standard_name," EQUIP ")>0
replace asstype = "firm" if strpos(standard_name," EQUIPAMENTOS ")>0
replace asstype = "firm" if strpos(standard_name," EQUIPEMENT ")>0
replace asstype = "firm" if strpos(standard_name," EQUIPEMENTS ")>0
replace asstype = "firm" if strpos(standard_name," EQUIPMENT ")>0
replace asstype = "firm" if strpos(standard_name," EST ")>0
replace asstype = "firm" if strpos(standard_name," ESTABILSSEMENTS ")>0
replace asstype = "firm" if strpos(standard_name," ESTABLISHMENT ")>0
replace asstype = "firm" if strpos(standard_name," ESTABLISSEMENT ")>0
replace asstype = "firm" if strpos(standard_name," ESTABLISSEMENTS ")>0
replace asstype = "firm" if strpos(standard_name," ESTABLISSMENTS ")>0
replace asstype = "firm" if strpos(standard_name," ET FILS ")>0
replace asstype = "firm" if strpos(standard_name," ETABLISSEMENT ")>0
replace asstype = "firm" if strpos(standard_name," ETABLISSMENTS ")>0
replace asstype = "firm" if strpos(standard_name," ETS ")>0
replace asstype = "firm" if strpos(standard_name," FABRIC ")>0
replace asstype = "firm" if strpos(standard_name," FABRICA ")>0
replace asstype = "firm" if strpos(standard_name," FABRICATION ")>0
replace asstype = "firm" if strpos(standard_name," FABRICATIONS ")>0
replace asstype = "firm" if strpos(standard_name," FABRICS ")>0
replace asstype = "firm" if strpos(standard_name," FABRIEKEN ")>0
replace asstype = "firm" if strpos(standard_name," FABRIK ")>0
replace asstype = "firm" if strpos(standard_name," FABRIQUE ")>0
replace asstype = "firm" if strpos(standard_name," FABRYKA ")>0
replace asstype = "firm" if strpos(standard_name," FACTORY ")>0
replace asstype = "firm" if strpos(standard_name," FEDERATED ")>0
replace asstype = "firm" if strpos(standard_name," FILM ")>0
replace asstype = "firm" if strpos(standard_name," FINANCIERE ")>0
replace asstype = "firm" if strpos(standard_name," FIRM ")>0
replace asstype = "firm" if strpos(standard_name," FIRMA ")>0
replace asstype = "firm" if strpos(standard_name," GBMH ")>0
replace asstype = "firm" if strpos(standard_name," GBR ")>0
replace asstype = "firm" if strpos(standard_name," GEBR ")>0
replace asstype = "firm" if strpos(standard_name," GEBROEDERS ")>0
replace asstype = "firm" if strpos(standard_name," GEBRUEDER ")>0
replace asstype = "firm" if strpos(standard_name," GENERALE POUR LES TECHNIQUES NOUVELLE ")>0
replace asstype = "firm" if strpos(standard_name," GENOSSENSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," GES M B H ")>0
replace asstype = "firm" if strpos(standard_name," GES MB H ")>0
replace asstype = "firm" if strpos(standard_name," GES MBH ")>0
replace asstype = "firm" if strpos(standard_name," GES MHH ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT M B ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MB H ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MBH ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MGH ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MIT ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MIT BESCHRANKTER ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFT MIT BESCHRANKTER HAFT ")>0
replace asstype = "firm" if strpos(standard_name," GESELLSCHAFTMIT BESCHRANKTER ")>0
replace asstype = "firm" if strpos(standard_name," GESMBH ")>0
replace asstype = "firm" if strpos(standard_name," GES ")>0
replace asstype = "firm" if strpos(standard_name," GESSELLSCHAFT MIT BESCHRAENKTER HAUFTUNG ")>0
replace asstype = "firm" if strpos(standard_name," GIE ")>0
replace asstype = "firm" if strpos(standard_name," GMBA ")>0
replace asstype = "firm" if strpos(standard_name," GMBB ")>0
replace asstype = "firm" if strpos(standard_name," GMBG ")>0
replace asstype = "firm" if strpos(standard_name," GMBH ")>0
replace asstype = "firm" if strpos(standard_name," GMHB ")>0
replace asstype = "firm" if strpos(standard_name," GNBH ")>0
replace asstype = "firm" if strpos(standard_name," GORPORATION ")>0
replace asstype = "firm" if strpos(standard_name," GROEP ")>0
replace asstype = "firm" if strpos(standard_name," GROUP ")>0
replace asstype = "firm" if strpos(standard_name," GROUPEMENT D ENTREPRISES ")>0
replace asstype = "firm" if strpos(standard_name," H ")>0
replace asstype = "firm" if strpos(standard_name," HAFRUNG ")>0
replace asstype = "firm" if strpos(standard_name," HANDEL ")>0
replace asstype = "firm" if strpos(standard_name," HANDELABOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," HANDELEND ONDER ")>0
replace asstype = "firm" if strpos(standard_name," HANDELORGANISATION ")>0
replace asstype = "firm" if strpos(standard_name," HANDELS ")>0
replace asstype = "firm" if strpos(standard_name," HANDELSBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," HANDELSBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," HANDELSGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," HANDESBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," HATFUNG ")>0
replace asstype = "firm" if strpos(standard_name," HB ")>0
replace asstype = "firm" if strpos(standard_name," HF ")>0
replace asstype = "firm" if strpos(standard_name," HOLDINGS ")>0
replace asstype = "firm" if strpos(standard_name," INC ")>0
replace asstype = "firm" if strpos(standard_name," INC: ")>0
replace asstype = "firm" if strpos(standard_name," INCOPORATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORORATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPARATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPORATE ")>0
replace asstype = "firm" if strpos(standard_name," INCORPORATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPORORATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPORTED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPOTATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPRATED ")>0
replace asstype = "firm" if strpos(standard_name," INCORPRORATED ")>0
replace asstype = "firm" if strpos(standard_name," INCROPORATED ")>0
replace asstype = "firm" if strpos(standard_name," INDISTRIES ")>0
replace asstype = "firm" if strpos(standard_name," INDUSRTIES ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRI ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIA ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIAL ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIAL COP ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIALNA ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIAS ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIE ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIES ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIJA ")>0
replace asstype = "firm" if strpos(standard_name," INDUSTRIJSKO ")>0
replace asstype = "firm" if strpos(standard_name," INGENIEURBUERO ")>0
replace asstype = "firm" if strpos(standard_name," INGENIEURBURO ")>0
replace asstype = "firm" if strpos(standard_name," INGENIEURGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," INGENIEURSBUERO ")>0
replace asstype = "firm" if strpos(standard_name," INGENIEURSBUREAU ")>0
replace asstype = "firm" if strpos(standard_name," INGENIOERSBYRA ")>0
replace asstype = "firm" if strpos(standard_name," INGENJOERSFIRMA ")>0
replace asstype = "firm" if strpos(standard_name," INGENJOERSFIRMAN ")>0
replace asstype = "firm" if strpos(standard_name," INORPORATED ")>0
replace asstype = "firm" if strpos(standard_name," INT ")>0
replace asstype = "firm" if strpos(standard_name," INT L ")>0
replace asstype = "firm" if strpos(standard_name," INTERNAITONAL ")>0
replace asstype = "firm" if strpos(standard_name," INTERNATIONAL ")>0
replace asstype = "firm" if strpos(standard_name," INTERNATIONAL BUSINESS ")>0
replace asstype = "firm" if strpos(standard_name," INTERNATIONALE ")>0
replace asstype = "firm" if strpos(standard_name," INTERNATIONAUX ")>0
replace asstype = "firm" if strpos(standard_name," INTERNTIONAL ")>0
replace asstype = "firm" if strpos(standard_name," INTL ")>0
replace asstype = "firm" if strpos(standard_name," INUDSTRIE ")>0
replace asstype = "firm" if strpos(standard_name," INVESTMENT ")>0
replace asstype = "firm" if strpos(standard_name," IS ")>0
replace asstype = "firm" if strpos(standard_name," JOINTVENTURE ")>0
replace asstype = "firm" if strpos(standard_name," K G ")>0
replace asstype = "firm" if strpos(standard_name," K K ")>0
replace asstype = "firm" if strpos(standard_name," KABAUSHIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABISHIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABSUHIKI ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHI KIKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIBI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKI ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKU KASISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHKIKI KAISHI ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKI ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKI KAISYA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKIKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAGUSHIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAUSHIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAISYA ")>0
replace asstype = "firm" if strpos(standard_name," KABAUSHIKI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABISHIKI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHI KIGAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIBI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIGAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKGAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHIKU GASISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSHKIKI GAISHI ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKI GAISYA ")>0
replace asstype = "firm" if strpos(standard_name," KABUSIKIGAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAGUSHIKI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KAUSHIKI GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," GAISHA ")>0
replace asstype = "firm" if strpos(standard_name," GAISYA ")>0
replace asstype = "firm" if strpos(standard_name," KB ")>0
replace asstype = "firm" if strpos(standard_name," KB KY ")>0
replace asstype = "firm" if strpos(standard_name," KFT ")>0
replace asstype = "firm" if strpos(standard_name," KG ")>0
replace asstype = "firm" if strpos(standard_name," KGAA ")>0
replace asstype = "firm" if strpos(standard_name," KK ")>0
replace asstype = "firm" if strpos(standard_name," KOM GES ")>0
replace asstype = "firm" if strpos(standard_name," KOMM GES ")>0
replace asstype = "firm" if strpos(standard_name," KOMMANDITBOLAG ")>0
replace asstype = "firm" if strpos(standard_name," KOMMANDITBOLAGET ")>0
replace asstype = "firm" if strpos(standard_name," KOMMANDITGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," KONSTRUKTIONEN ")>0
replace asstype = "firm" if strpos(standard_name," KOOPERATIVE ")>0
replace asstype = "firm" if strpos(standard_name," KS ")>0
replace asstype = "firm" if strpos(standard_name," KUBUSHIKI KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," KY ")>0
replace asstype = "firm" if strpos(standard_name," L ")>0
replace asstype = "firm" if strpos(standard_name," L C ")>0
replace asstype = "firm" if strpos(standard_name," L L C ")>0
replace asstype = "firm" if strpos(standard_name," L P ")>0
replace asstype = "firm" if strpos(standard_name," LAB ")>0
replace asstype = "firm" if strpos(standard_name," LABARATOIRE ")>0
replace asstype = "firm" if strpos(standard_name," LABO ")>0
replace asstype = "firm" if strpos(standard_name," LABORATOIRE ")>0
replace asstype = "firm" if strpos(standard_name," LABORATOIRES ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORI ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORIA ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORIE ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORIES ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORIET ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORIUM ")>0
replace asstype = "firm" if strpos(standard_name," LABORATORY ")>0
replace asstype = "firm" if strpos(standard_name," LABRATIORIES ")>0
replace asstype = "firm" if strpos(standard_name," LABS ")>0
replace asstype = "firm" if strpos(standard_name," LC ")>0
replace asstype = "firm" if strpos(standard_name," LCC ")>0
replace asstype = "firm" if strpos(standard_name," LDA ")>0
replace asstype = "firm" if strpos(standard_name," LDT ")>0
replace asstype = "firm" if strpos(standard_name," LIIMITED ")>0
replace asstype = "firm" if strpos(standard_name," LIMIDADA ")>0
replace asstype = "firm" if strpos(standard_name," LIMINTED ")>0
replace asstype = "firm" if strpos(standard_name," LIMITADA ")>0
replace asstype = "firm" if strpos(standard_name," LIMITADO ")>0
replace asstype = "firm" if strpos(standard_name," LIMITATA ")>0
replace asstype = "firm" if strpos(standard_name," LIMITE ")>0
replace asstype = "firm" if strpos(standard_name," LIMITED ")>0
replace asstype = "firm" if strpos(standard_name," LIMITEE ")>0
replace asstype = "firm" if strpos(standard_name," LIMTED ")>0
replace asstype = "firm" if strpos(standard_name," LINITED ")>0
replace asstype = "firm" if strpos(standard_name," LITD ")>0
replace asstype = "firm" if strpos(standard_name," LLC ")>0
replace asstype = "firm" if strpos(standard_name," LLLC ")>0
replace asstype = "firm" if strpos(standard_name," LLLP ")>0
replace asstype = "firm" if strpos(standard_name," LLP ")>0
replace asstype = "firm" if strpos(standard_name," LMITED ")>0
replace asstype = "firm" if strpos(standard_name," LP ")>0
replace asstype = "firm" if strpos(standard_name," LT EE ")>0
replace asstype = "firm" if strpos(standard_name," LTA ")>0
replace asstype = "firm" if strpos(standard_name," LTC ")>0
replace asstype = "firm" if strpos(standard_name," LTD ")>0
replace asstype = "firm" if strpos(standard_name," LTD: ")>0
replace asstype = "firm" if strpos(standard_name," LTDA ")>0
replace asstype = "firm" if strpos(standard_name," LTDS ")>0
replace asstype = "firm" if strpos(standard_name," LTEE ")>0
replace asstype = "firm" if strpos(standard_name," LTEE; ")>0
replace asstype = "firm" if strpos(standard_name," LTS ")>0
replace asstype = "firm" if strpos(standard_name," MAATSCHAPPIJ ")>0
replace asstype = "firm" if strpos(standard_name," MANUFACTURE ")>0
replace asstype = "firm" if strpos(standard_name," MANUFACTURE D ARTICLES ")>0
replace asstype = "firm" if strpos(standard_name," MANUFACTURE DE ")>0
replace asstype = "firm" if strpos(standard_name," MANUFACTURING ")>0
replace asstype = "firm" if strpos(standard_name," MARKETING ")>0
replace asstype = "firm" if strpos(standard_name," MASCHINENBAU ")>0
replace asstype = "firm" if strpos(standard_name," MASCHINENFABRIK ")>0
replace asstype = "firm" if strpos(standard_name," MBH ")>0
replace asstype = "firm" if strpos(standard_name," MBH & CO ")>0
replace asstype = "firm" if strpos(standard_name," MERCHANDISING ")>0
replace asstype = "firm" if strpos(standard_name," MET BEPERKTE ")>0
replace asstype = "firm" if strpos(standard_name," MFG ")>0
replace asstype = "firm" if strpos(standard_name," N A ")>0
replace asstype = "firm" if strpos(standard_name," N V ")>0
replace asstype = "firm" if strpos(standard_name," NA ")>0
replace asstype = "firm" if strpos(standard_name," NAAMLOSE ")>0
replace asstype = "firm" if strpos(standard_name," NAAMLOZE ")>0
replace asstype = "firm" if strpos(standard_name," NAAMLOZE VENNOOTSCAP ")>0
replace asstype = "firm" if strpos(standard_name," NAAMLOZE VENNOOTSHCAP ")>0
replace asstype = "firm" if strpos(standard_name," NAAMLOZEVENNOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO PRIOZVODSTVENNAYA FIRMA ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO PRIOZVODSTVENNOE OBIEDINENIE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO PRIOZVODSTVENNY KOOPERATIV ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO PROIZVODSTVENNOE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO PROIZVODSTVENNOE OBJEDINENIE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO TEKHNICHESKY KOOPERATIV ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO TEKHNICHESKYKKOOPERATIV ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO TEKHNOLOGICHESKOE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNO TEKHNOLOGICHESKOEPREDPRIYATIE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNOPRIOZVODSTVENNOE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNOPROIZVODSTVENNOE ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNOTEKHNICHESKYKKOOPERATIV ")>0
replace asstype = "firm" if strpos(standard_name," NAUCHNOTEKNICHESKY ")>0
replace asstype = "firm" if strpos(standard_name," NV ")>0
replace asstype = "firm" if strpos(standard_name," NV SA ")>0
replace asstype = "firm" if strpos(standard_name," NV: ")>0
replace asstype = "firm" if strpos(standard_name," NVSA ")>0
replace asstype = "firm" if strpos(standard_name," OBIDINENIE ")>0
replace asstype = "firm" if strpos(standard_name," OBIED ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESRYO ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO & OGRANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO & ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO C ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENNOI ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENNOI OTVETSTVEN NOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENNOI OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENNOI OTVETSTVENNPSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENNOY OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S OGRANICHENOI ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSCHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSHESTVO S ")>0
replace asstype = "firm" if strpos(standard_name," OBSHESTVO S OGRANNICHENNOJ ")>0
replace asstype = "firm" if strpos(standard_name," OBSHESTVO S ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OBSHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OCTROOIBUREAU ")>0
replace asstype = "firm" if strpos(standard_name," OGRANICHENNOI OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OGRANICHENNOI OTVETSTVENNOSTIJU FIRMA ")>0
replace asstype = "firm" if strpos(standard_name," OGRANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OGRANICHENNOY OTVETSTVENNOSTYU ")>0
replace asstype = "firm" if strpos(standard_name," OHG ")>0
replace asstype = "firm" if strpos(standard_name," ONDERNEMING ")>0
replace asstype = "firm" if strpos(standard_name," OTVETCTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OTVETSTVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," OTVETSTVENNOSTOU ")>0
replace asstype = "firm" if strpos(standard_name," OTVETSTVENNOSTYU ")>0
replace asstype = "firm" if strpos(standard_name," OY ")>0
replace asstype = "firm" if strpos(standard_name," OYABLTD ")>0
replace asstype = "firm" if strpos(standard_name," OYG ")>0
replace asstype = "firm" if strpos(standard_name," OYI ")>0
replace asstype = "firm" if strpos(standard_name," OYJ ")>0
replace asstype = "firm" if strpos(standard_name," OYL ")>0
replace asstype = "firm" if strpos(standard_name," P ")>0
replace asstype = "firm" if strpos(standard_name," P C ")>0
replace asstype = "firm" if strpos(standard_name," P L C ")>0
replace asstype = "firm" if strpos(standard_name," PARNERSHIP ")>0
replace asstype = "firm" if strpos(standard_name," PARNTERSHIP ")>0
replace asstype = "firm" if strpos(standard_name," PARTNER ")>0
replace asstype = "firm" if strpos(standard_name," PARTNERS ")>0
replace asstype = "firm" if strpos(standard_name," PARTNERSHIP ")>0
replace asstype = "firm" if strpos(standard_name," PATENT OFFICE ")>0
replace asstype = "firm" if strpos(standard_name," PATENTVERWALTUNGS GESELLSCHAFT MBH ")>0
replace asstype = "firm" if strpos(standard_name," PATENTVERWALTUNGSGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," PATENTVERWERTUNGSGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," PATNERSHIP ")>0
replace asstype = "firm" if strpos(standard_name," PC ")>0
replace asstype = "firm" if strpos(standard_name," PER AZIONA ")>0
replace asstype = "firm" if strpos(standard_name," PERSONENVENNOOTSCHAP MET BE PERKTE AANSPRAKELIJKHEID ")>0
replace asstype = "firm" if strpos(standard_name," PHARM ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACEUTICA ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACEUTICAL ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACEUTICALS ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACEUTIQUE ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACIA ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACIE ")>0
replace asstype = "firm" if strpos(standard_name," PHARMACUETICALS ")>0
replace asstype = "firm" if strpos(standard_name," PLANTS ")>0
replace asstype = "firm" if strpos(standard_name," PLC ")>0
replace asstype = "firm" if strpos(standard_name," PREDPRIVATIE ")>0
replace asstype = "firm" if strpos(standard_name," PREDPRIYATIE ")>0
replace asstype = "firm" if strpos(standard_name," PREPRIVATIE ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCE ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCT ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCTEURS ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCTION ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCTIONS ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCTIQUE ")>0
replace asstype = "firm" if strpos(standard_name," PRODUCTS ")>0
replace asstype = "firm" if strpos(standard_name," PRODUITS ")>0
replace asstype = "firm" if strpos(standard_name," PRODUKTE ")>0
replace asstype = "firm" if strpos(standard_name," PRODUKTER ")>0
replace asstype = "firm" if strpos(standard_name," PRODUKTION ")>0
replace asstype = "firm" if strpos(standard_name," PRODUKTIONSGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," PRODUKTUTVECKLING ")>0
replace asstype = "firm" if strpos(standard_name," PRODURA ")>0
replace asstype = "firm" if strpos(standard_name," PRODUTIS ")>0
replace asstype = "firm" if strpos(standard_name," PROIZVODSTENNOE OBIEDINENIE ")>0
replace asstype = "firm" if strpos(standard_name," PROIZVODSTVENNOE ")>0
replace asstype = "firm" if strpos(standard_name," PROIZVODSTVENNOE OBIEDINENIE ")>0
replace asstype = "firm" if strpos(standard_name," PTY ")>0
replace asstype = "firm" if strpos(standard_name," PTY LIM ")>0
replace asstype = "firm" if strpos(standard_name," PTYLTD ")>0
replace asstype = "firm" if strpos(standard_name," PUBLISHING ")>0
replace asstype = "firm" if strpos(standard_name," PVBA ")>0
replace asstype = "firm" if strpos(standard_name," RECHERCHES ")>0
replace asstype = "firm" if strpos(standard_name," RESPONSABILITA LIMITATA ")>0
replace asstype = "firm" if strpos(standard_name," RESPONSABILITA’ LIMITATA ")>0
replace asstype = "firm" if strpos(standard_name," RESPONSABILITE LIMITE ")>0
replace asstype = "firm" if strpos(standard_name," RO ")>0
replace asstype = "firm" if strpos(standard_name," RT ")>0
replace asstype = "firm" if strpos(standard_name," S A ")>0
replace asstype = "firm" if strpos(standard_name," S A R L ")>0
replace asstype = "firm" if strpos(standard_name," S A RL ")>0
replace asstype = "firm" if strpos(standard_name," S COOP ")>0
replace asstype = "firm" if strpos(standard_name," S COOP LTDA ")>0
replace asstype = "firm" if strpos(standard_name," S NC ")>0
replace asstype = "firm" if strpos(standard_name," S OGRANICHENNOI OTVETSTVENNEST ")>0
replace asstype = "firm" if strpos(standard_name," S P A ")>0
replace asstype = "firm" if strpos(standard_name," S PA ")>0
replace asstype = "firm" if strpos(standard_name," S R L ")>0
replace asstype = "firm" if strpos(standard_name," S RL ")>0
replace asstype = "firm" if strpos(standard_name," S S ")>0
replace asstype = "firm" if strpos(standard_name," SA ")>0
replace asstype = "firm" if strpos(standard_name," SA A RL ")>0
replace asstype = "firm" if strpos(standard_name," SA RL ")>0
replace asstype = "firm" if strpos(standard_name," SA: ")>0
replace asstype = "firm" if strpos(standard_name," SAAG ")>0
replace asstype = "firm" if strpos(standard_name," SAARL ")>0
replace asstype = "firm" if strpos(standard_name," SALES ")>0
replace asstype = "firm" if strpos(standard_name," SANV ")>0
replace asstype = "firm" if strpos(standard_name," SARL ")>0
replace asstype = "firm" if strpos(standard_name," SARL: ")>0
replace asstype = "firm" if strpos(standard_name," SAS ")>0
replace asstype = "firm" if strpos(standard_name," SC ")>0
replace asstype = "firm" if strpos(standard_name," SCA ")>0
replace asstype = "firm" if strpos(standard_name," SCARL ")>0
replace asstype = "firm" if strpos(standard_name," SCIETE ANONYME ")>0
replace asstype = "firm" if strpos(standard_name," SCOOP ")>0
replace asstype = "firm" if strpos(standard_name," SCPA ")>0
replace asstype = "firm" if strpos(standard_name," SCRAS ")>0
replace asstype = "firm" if strpos(standard_name," SCRL ")>0
replace asstype = "firm" if strpos(standard_name," SEMPLICE ")>0
replace asstype = "firm" if strpos(standard_name," SERIVICES ")>0
replace asstype = "firm" if strpos(standard_name," SERVICE ")>0
replace asstype = "firm" if strpos(standard_name," SERVICES ")>0
replace asstype = "firm" if strpos(standard_name," SHOP ")>0
replace asstype = "firm" if strpos(standard_name," SIMPLIFIEE ")>0
replace asstype = "firm" if strpos(standard_name," SL ")>0
replace asstype = "firm" if strpos(standard_name," SNC ")>0
replace asstype = "firm" if strpos(standard_name," SOC ")>0
replace asstype = "firm" if strpos(standard_name," SOC ARL ")>0
replace asstype = "firm" if strpos(standard_name," SOC COOOP ARL ")>0
replace asstype = "firm" if strpos(standard_name," SOC COOP A RESP LIM ")>0
replace asstype = "firm" if strpos(standard_name," SOC COOP A RL ")>0
replace asstype = "firm" if strpos(standard_name," SOC COOP R L ")>0
replace asstype = "firm" if strpos(standard_name," SOC COOP RL ")>0
replace asstype = "firm" if strpos(standard_name," SOC IND COMM ")>0
replace asstype = "firm" if strpos(standard_name," SOC RL ")>0
replace asstype = "firm" if strpos(standard_name," SOCCOOP ARL ")>0
replace asstype = "firm" if strpos(standard_name," SOCCOOPARL ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDAD ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDAD ANONIMA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDAD ANONIMYA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDAD INDUSTRIAL ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDAD LIMITADA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIEDADE LIMITADA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIET CIVILE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA A ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA A RESPONSABILITA LIMITATA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA ANONIMA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA CONSORTILE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA CONSORTILE A RESPONSABILITA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA CONSORTILE ARL ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA CONSORTILE PER AZION ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA CONSORTILE PER AZIONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA COOPERATIVA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA COOPERATIVA A ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA IN ACCOMANDITA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA IN ACCOMANDITA SEMPLICE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA IN NOME COLLETTIVO ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA INDUSTRIA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER AXIONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER AZINOI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER AZINONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER AZIONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER AZIONI: ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PER L INDUSTRIA ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETA PERAZIONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETAPERAZIONI ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE A ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE A RESPONSABILITE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE A RESPONSABILITE DITE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE A RESPONSABILITEE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANANYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANNOYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANOMYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANOMYNE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANONVME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANONYM ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANONYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ANOYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE CHIMIQUE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE CIVILE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE COOPERATIVE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D APPLICATIONS GENERALES ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D APPLICATIONS MECANIQUES ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D EQUIPEMENT ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D ETUDE ET DE CONSTRUCTION ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D ETUDE ET DE RECHERCHE EN VENTILATION ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D ETUDES ET ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE D ETUDES TECHNIQUES ET D ENTREPRISES ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE CONSEILS DE RECHERCHES ET D APPLICATIONS ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE CONSTRUCTIO ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE FABRICAITON ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE FABRICATION ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DE PRODUCTION ET DE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DES TRANSPORTS ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DITE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DITE : ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE DITE: ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE EN ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE EN COMMANDITE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE EN COMMANDITE ENREGISTREE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE EN NOM COLLECTIF ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ETUDES ET ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE ETUDES ET DEVELOPPEMENTS ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE GENERALE POUR LES ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE GENERALE POUR LES TECHNIQUES NOVELLES ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE METALLURGIQUE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE NOUVELLE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE PAR ACTIONS ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE PAR ACTIONS SIMPLIFEE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE PAR ACTIONS SIMPLIFIEE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE TECHNIQUE D APPLICATION ET DE RECHERCHE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETE TECHNIQUE DE PULVERISATION ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETEANONYME ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETEDITE ")>0
replace asstype = "firm" if strpos(standard_name," SOCIETEINDUSTRIELLE ")>0
replace asstype = "firm" if strpos(standard_name," SOCRL ")>0
replace asstype = "firm" if strpos(standard_name," SOEHNE ")>0
replace asstype = "firm" if strpos(standard_name," SOGRANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," SOHN ")>0
replace asstype = "firm" if strpos(standard_name," SOHNE ")>0
replace asstype = "firm" if strpos(standard_name," SONNER ")>0
replace asstype = "firm" if strpos(standard_name," SP ")>0
replace asstype = "firm" if strpos(standard_name," SP A ")>0
replace asstype = "firm" if strpos(standard_name," SP Z OO ")>0
replace asstype = "firm" if strpos(standard_name," SP ZOO ")>0
replace asstype = "firm" if strpos(standard_name," SPA ")>0
replace asstype = "firm" if strpos(standard_name," SPOKAZOO ")>0
replace asstype = "firm" if strpos(standard_name," SPOL ")>0
replace asstype = "firm" if strpos(standard_name," SPOL S R O ")>0
replace asstype = "firm" if strpos(standard_name," SPOL S RO ")>0
replace asstype = "firm" if strpos(standard_name," SPOL SRO ")>0
replace asstype = "firm" if strpos(standard_name," SPOLECNOST SRO ")>0
replace asstype = "firm" if strpos(standard_name," SPOLKA Z OO ")>0
replace asstype = "firm" if strpos(standard_name," SPOLKA ZOO ")>0
replace asstype = "firm" if strpos(standard_name," SPOLS RO ")>0
replace asstype = "firm" if strpos(standard_name," SPOLSRO ")>0
replace asstype = "firm" if strpos(standard_name," SPRL ")>0
replace asstype = "firm" if strpos(standard_name," SPZ OO ")>0
replace asstype = "firm" if strpos(standard_name," SPZOO ")>0
replace asstype = "firm" if strpos(standard_name," SR ")>0
replace asstype = "firm" if strpos(standard_name," SR L ")>0
replace asstype = "firm" if strpos(standard_name," SR1 ")>0
replace asstype = "firm" if strpos(standard_name," SRI ")>0
replace asstype = "firm" if strpos(standard_name," SRL ")>0
replace asstype = "firm" if strpos(standard_name," SRO ")>0
replace asstype = "firm" if strpos(standard_name," SßRL ")>0
replace asstype = "firm" if strpos(standard_name," SURL ")>0
replace asstype = "firm" if strpos(standard_name," TEAM ")>0
replace asstype = "firm" if strpos(standard_name," TECHNIQUES NOUVELLE ")>0
replace asstype = "firm" if strpos(standard_name," TECHNOLOGIES ")>0
replace asstype = "firm" if strpos(standard_name," THE FIRM ")>0
replace asstype = "firm" if strpos(standard_name," TOHO BUSINESS ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESIVO S OGRANICHENNOI OIVETSIVENNOSTIJU ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESTVO ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESTVO S OGRANICHENNOI ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESTVO S OGRANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESTVO S OGRANICHENNOI OTVETSVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
replace asstype = "firm" if strpos(standard_name," TOVARISCHETSTVO S ORGANICHENNOI ")>0
replace asstype = "firm" if strpos(standard_name," TRADING ")>0
replace asstype = "firm" if strpos(standard_name," TRADING AS ")>0
replace asstype = "firm" if strpos(standard_name," TRADING UNDER ")>0
replace asstype = "firm" if strpos(standard_name," UGINE ")>0
replace asstype = "firm" if strpos(standard_name," UNTERNEHMEN ")>0
replace asstype = "firm" if strpos(standard_name," USA ")>0
replace asstype = "firm" if strpos(standard_name," USINES ")>0
replace asstype = "firm" if strpos(standard_name," VAKMANSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," VENNOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," VENNOOTSCHAP ONDER FIRMA: ")>0
replace asstype = "firm" if strpos(standard_name," VENNOOTSHAP ")>0
replace asstype = "firm" if strpos(standard_name," VENNOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," VENOOTSCHAP ")>0
replace asstype = "firm" if strpos(standard_name," VENTURE ")>0
replace asstype = "firm" if strpos(standard_name," VERARBEITUNG ")>0
replace asstype = "firm" if strpos(standard_name," VERKOOP ")>0
replace asstype = "firm" if strpos(standard_name," VERSICHERUNGSBUERO ")>0
replace asstype = "firm" if strpos(standard_name," VERTRIEBSGESELLSCHAFT ")>0
replace asstype = "firm" if strpos(standard_name," VOF ")>0
replace asstype = "firm" if strpos(standard_name," WERK ")>0
replace asstype = "firm" if strpos(standard_name," WERKE ")>0
replace asstype = "firm" if strpos(standard_name," WERKEN ")>0
replace asstype = "firm" if strpos(standard_name," WERKHUIZEN ")>0
replace asstype = "firm" if strpos(standard_name," WERKS ")>0
replace asstype = "firm" if strpos(standard_name," WERKSTAETTE ")>0
replace asstype = "firm" if strpos(standard_name," WERKSTATT ")>0
replace asstype = "firm" if strpos(standard_name," WERKZEUGBAU ")>0
replace asstype = "firm" if strpos(standard_name," WINKEL ")>0
replace asstype = "firm" if strpos(standard_name," WORKS ")>0
replace asstype = "firm" if strpos(standard_name," YUGEN KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," YUGENKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," YUUGEN KAISHA ")>0
replace asstype = "firm" if strpos(standard_name," YUUGENKAISHA ")>0
replace asstype = "firm" if strpos(standard_name," ZOO ")>0

** remove double spaces
replace standard_name = subinstr(standard_name,"  "," ",30)
